name: Build and Release
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1

      - name: Install dependencies
        run: flutter pub get
        working-directory: app

      - name: Run tests
        run: flutter test
        working-directory: app

      - name: Build APK
        run: flutter build apk
        working-directory: app

      - name: Build App Bundle
        run: flutter build appbundle
        working-directory: app

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/app/outputs/flutter-apk/app-release.apk
            app/build/app/outputs/bundle/release/app-release.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
